//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chaos.Movies.Model.ChaosMovieService {
    using System;
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateTimeFormatFlags", Namespace="http://schemas.datacontract.org/2004/07/System.Globalization")]
    public enum DateTimeFormatFlags : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseGenitiveMonth = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseLeapYearMonth = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseSpacesInMonthNames = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseHebrewRule = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseSpacesInDayNames = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseDigitPrefixInTokens = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotInitialized = -1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChaosMovieService.IChaosMoviesService")]
    public interface IChaosMoviesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChaosMoviesService/CreateUserSession", ReplyAction="http://tempuri.org/IChaosMoviesService/CreateUserSessionResponse")]
        Chaos.Movies.Contract.UserSessionDto CreateUserSession(Chaos.Movies.Contract.UserSessionDto session, Chaos.Movies.Contract.UserLogin userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChaosMoviesService/CreateUserSession", ReplyAction="http://tempuri.org/IChaosMoviesService/CreateUserSessionResponse")]
        System.Threading.Tasks.Task<Chaos.Movies.Contract.UserSessionDto> CreateUserSessionAsync(Chaos.Movies.Contract.UserSessionDto session, Chaos.Movies.Contract.UserLogin userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChaosMoviesService/CharacterSave", ReplyAction="http://tempuri.org/IChaosMoviesService/CharacterSaveResponse")]
        void CharacterSave(Chaos.Movies.Contract.UserSessionDto session, Chaos.Movies.Contract.CharacterDto character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChaosMoviesService/CharacterSave", ReplyAction="http://tempuri.org/IChaosMoviesService/CharacterSaveResponse")]
        System.Threading.Tasks.Task CharacterSaveAsync(Chaos.Movies.Contract.UserSessionDto session, Chaos.Movies.Contract.CharacterDto character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChaosMoviesService/CharacterGet", ReplyAction="http://tempuri.org/IChaosMoviesService/CharacterGetResponse")]
        System.Collections.Generic.List<Chaos.Movies.Contract.CharacterDto> CharacterGet(Chaos.Movies.Contract.UserSessionDto session, System.Collections.Generic.List<int> idList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChaosMoviesService/CharacterGet", ReplyAction="http://tempuri.org/IChaosMoviesService/CharacterGetResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Chaos.Movies.Contract.CharacterDto>> CharacterGetAsync(Chaos.Movies.Contract.UserSessionDto session, System.Collections.Generic.List<int> idList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChaosMoviesServiceChannel : Chaos.Movies.Model.ChaosMovieService.IChaosMoviesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChaosMoviesServiceClient : System.ServiceModel.ClientBase<Chaos.Movies.Model.ChaosMovieService.IChaosMoviesService>, Chaos.Movies.Model.ChaosMovieService.IChaosMoviesService {
        
        public ChaosMoviesServiceClient() {
        }
        
        public ChaosMoviesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChaosMoviesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChaosMoviesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChaosMoviesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Chaos.Movies.Contract.UserSessionDto CreateUserSession(Chaos.Movies.Contract.UserSessionDto session, Chaos.Movies.Contract.UserLogin userLogin) {
            return base.Channel.CreateUserSession(session, userLogin);
        }
        
        public System.Threading.Tasks.Task<Chaos.Movies.Contract.UserSessionDto> CreateUserSessionAsync(Chaos.Movies.Contract.UserSessionDto session, Chaos.Movies.Contract.UserLogin userLogin) {
            return base.Channel.CreateUserSessionAsync(session, userLogin);
        }
        
        public void CharacterSave(Chaos.Movies.Contract.UserSessionDto session, Chaos.Movies.Contract.CharacterDto character) {
            base.Channel.CharacterSave(session, character);
        }
        
        public System.Threading.Tasks.Task CharacterSaveAsync(Chaos.Movies.Contract.UserSessionDto session, Chaos.Movies.Contract.CharacterDto character) {
            return base.Channel.CharacterSaveAsync(session, character);
        }
        
        public System.Collections.Generic.List<Chaos.Movies.Contract.CharacterDto> CharacterGet(Chaos.Movies.Contract.UserSessionDto session, System.Collections.Generic.List<int> idList) {
            return base.Channel.CharacterGet(session, idList);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Chaos.Movies.Contract.CharacterDto>> CharacterGetAsync(Chaos.Movies.Contract.UserSessionDto session, System.Collections.Generic.List<int> idList) {
            return base.Channel.CharacterGetAsync(session, idList);
        }
    }
}
